---
- name: configure jenkins repo
  include: repos.yml
  tags:
    - jenkins
    - repos
    - packages

- name: install java
  yum: name=java state=present
  tags:
    - jenkins
    - packages

- name: install jenkins
  yum: name=jenkins state=present
  tags:
    - jenkins
    - packages

- name: configure jenkins startup
  template: src=sysconfig.j2 dest=/etc/sysconfig/jenkins owner=root group=root mode=0600
  notify: restart jenkins
  tags:
    - jenkins
    - configuration

- name: ensure jenkins is enabled and running
  service: name=jenkins enabled=yes state=started
  tags:
    - jenkins
    - configuration
    - services

- name: open jenkins port
  firewalld: port={{ jenkins_port }}/tcp permanent=true state=enabled
  when: jenkins_open_port
  notify: reload firewall
  tags:
    - jenkins
    - configuration
    - firewall

- name: open jenkins ajp port
  firewalld: port={{ jenkins_ajp_port }}/tcp permanent=true state=enabled
  when: jenkins_open_ajp_port
  notify: reload firewall
  tags:
    - jenkins
    - configuration
    - firewall